const Utwory = 
    [
        ["1788","https://www.youtube.com/watch?v=VtsMVI8Fles"],
        ["afganistan","https://www.youtube.com/watch?v=LymahcG-hBc"],
        ["akompaniator","https://www.youtube.com/watch?v=lXdRQ612l9g"], // GŁOS ŁAPIŃSKI
        ["aleksander","https://www.youtube.com/watch?v=cyO786KOPMg"],
        ["amanci","https://www.youtube.com/watch?v=aAO4fant-qk"],
        ["ambasadorowie","https://www.youtube.com/watch?v=ky24tma746g"],
        ["amyniechcemy","https://www.youtube.com/watch?v=ubEvODY4j1M"],
        ["antylitania","https://www.youtube.com/watch?v=eNzCit7d9Kw"],
        ["ararat","https://www.youtube.com/watch?v=j6yHeqQDx9Q"],
        ["arka","https://www.youtube.com/watch?v=GzxeaC896mU"],             ///// BRAK ZNALEZIONEGO UTOWRU ARKA 2
        ["artysci","https://www.youtube.com/watch?v=DC_ZwpVWPCQ"],
        ["astrolog","https://www.youtube.com/watch?v=XeMD0vZ4G-0"],  // GŁOS GINTROWSKi
        ["autoportret","https://www.youtube.com/watch?v=dPN_5G935Vw"],
        ["autoportretgin","https://www.youtube.com/watch?v=QTIJeROtF48"], //GŁOS GINTROWSKI
        ["autportretopsie","https://www.youtube.com/watch?v=4Q0O2eYV_mg"],
        ["bajeczka","https://www.youtube.com/watch?v=ZnzWQmkIU4g"],
        ["bajka","https://www.youtube.com/watch?v=b_6XgrK31lY"],
        ["bajkaopl","https://www.youtube.com/watch?v=39sUrIv4_3c"],
        ["bajkasr","https://www.youtube.com/watch?v=FiDsTVtEiBE"],
        ["bal","https://www.youtube.com/watch?v=zEZB0U5okVU"],
        ["bantykryzys","https://www.youtube.com/watch?v=a-2VX2rqkmw"],
        ["bczarnobiala","https://www.youtube.com/watch?v=vgjY0kTFJEU"],
        ["bdlaobywatela","https://www.youtube.com/watch?v=J4Vu2uQXcJI"],
        ["bfeudalna","https://www.youtube.com/watch?v=ZbfJ4Bg9AUo"],
        ["bobieli","https://www.youtube.com/watch?v=9LrEzTkZo2Y"],
        ["bobestii","https://www.youtube.com/watch?v=9XDMLBpP7Mg"],
        ["bohidalgu","https://www.youtube.com/watch?v=e138GDr0U68"],
        ["boistotkach","https://www.youtube.com/watch?v=1TXLiQDbd1c"],
        ["bookrzykach","https://www.youtube.com/watch?v=mA3jbTgpIAY"],
        ["bopowitaniu","https://www.youtube.com/watch?v=YqInc2WzLHo"],
        ["bosynagodze","https://www.youtube.com/watch?v=iF37u6fZcdc"],
        ["bospotkaniu","https://www.youtube.com/watch?v=YZ9XZBvWWGA"],
        ["boalkoholizmie","https://www.youtube.com/watch?v=VILElHYr0-w"],
        ["bomiasteczku","https://www.youtube.com/watch?v=VNMvYeC9zgI"],
        ["bowindzie","https://www.youtube.com/watch?v=rOuR9ZVkaWE"],
        ["bparanoika","https://www.youtube.com/watch?v=0ssw4MRwZN0"],
        ["bpozytywna","https://www.youtube.com/watch?v=9Yt4ODG71Gg"],
        ["bwrzesniowa","https://www.youtube.com/watch?v=XHZSp9VUw4A"],
        ["bzebracza","https://www.youtube.com/watch?v=EODgeIigxlQ"],
        ["baluboga","https://www.youtube.com/watch?v=pgciq_leSL8"],
        ["bankierzy","https://www.youtube.com/watch?v=orqCOjVIsV4"],     
        ["bankiet","https://www.youtube.com/watch?v=Nu8odTHHCHw"],
        ["baran","https://www.youtube.com/watch?v=j0f7V314JPk"],
        ["baranek","https://www.youtube.com/watch?v=Lurb4emrWkg"],
        ["bar","https://www.youtube.com/watch?v=m2QSXN-lpJU"],
        ["barykada","https://www.youtube.com/watch?v=-WivWJowtis"],
        ["bieg","https://www.youtube.com/watch?v=pMk0MqQ8B4M"],
        ["birkenau","https://www.youtube.com/watch?v=7LoNQkDDJLU"], //GŁOS GINTROWSKI
        ["bledywrozbitow","https://www.youtube.com/watch?v=F2Otp5a35kA"], //GLOS GINTROWSKI
        ["blogoslawiezlo","https://www.youtube.com/watch?v=R7cAMn2CbPc"],
        ["bluesodyssa","https://www.youtube.com/watch?v=kRJeRCPpYMk"],
        ["blues","https://www.youtube.com/watch?v=7Xr_gvFN604"],
        ["bob","https://www.youtube.com/watch?v=1BBJvykyGao"],
        ["brat","https://www.youtube.com/watch?v=okrzEIngwTo"],
        ["casanova","https://www.youtube.com/watch?v=sVNbY624Cmg"],
        ["celina","https://www.youtube.com/watch?v=H9I0PW4j3XQ"],
        ["cervantes","https://www.youtube.com/watch?v=qmJhSVU7K8s"],
        ["chrystus","https://www.youtube.com/watch?v=fUo5hl11JQo"],              
        ["ciagdalszy","https://www.youtube.com/watch?v=n6SjxtqAcDM"],
        ["ciezkideszcz","https://www.youtube.com/watch?v=8UNITzFOLQ0"],     
        ["ciwszyscyludzie","https://www.youtube.com/watch?v=PG7vaVx2La8"],
        ["codwochwidzi","https://www.youtube.com/watch?v=yYqW2npiDVY"], //GŁOS KACZMARCZYK
        ["costy","https://www.youtube.com/watch?v=AbMFRoRQkig"],
        ["coszacos","https://www.youtube.com/watch?v=9U3FO3ofDf0"],
        ["cromwell","https://www.youtube.com/watch?v=GiQZ4jL7H7M"],
        ["czarnesuchary","https://www.youtube.com/watch?v=56FaVP10XMY"],
        ["czary","https://www.youtube.com/watch?v=pzSgbL9ngTY"],
        ["czarnobyl","https://www.youtube.com/watch?v=morE4m_Zd4Y"],
        ["czastuszki","https://www.youtube.com/watch?v=O_PCMNOxppY"],
        ["czaty","https://www.youtube.com/watch?v=lCVbFKM-RAg"],
        ["czerwcowywicher","https://www.youtube.com/watch?v=Ggjbl33oz8o"],
        ["czerwonyautobus","https://www.youtube.com/watch?v=8ldFFu5-mVU"],
        ["czolg","https://www.youtube.com/watch?v=yCeuV682y6w"],
        //["dawid",""],
        ["deby","https://www.youtube.com/watch?v=yQkV4Y26c3A"],
        //["dennis",""],
        ["diabel","https://www.youtube.com/watch?v=RMItqEvi7mY"],
        ["dobrerady","https://www.youtube.com/watch?v=atio51Azl3E"],             
        /*["",""],
        ["",""],     
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],   
        ["",""],
        ["",""],     
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],   */
        ["ja", "https://www.youtube.com/watch?v=O_eYztVDVcw"],
        /*["",""],
        ["",""],     
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],
        ["",""],   */
        ["kantyczka", "https://www.youtube.com/watch?v=GXAEIPoxNew"],  
        ["katyn", "https://www.youtube.com/watch?v=QBVv7zMlksY"]

    ]

exports.Utwory = Utwory;